CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
POST_TITLE VARCHAR2(255) NOT NULL,
   POST_CONTENT VARCHAR2(255) NOT NULL,
   MEMBER_ID VARCHAR2(255) NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE
);
DROP TABLE TBL_POST;
DROP SEQUENCE SEQ_POST;
SELECT * FROM TBL_POST;