CREATE TABLE TBL_REPLY(
ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
REPLY_CONTENT VARCHAR2(255) NOT NULL,
POST_ID VARCHAR2(255) NOT NULL,
MEMBER_ID VARCHAR2(255) NOT NULL,
CREATED_DATE DATE DEFAULT SYSDATE,
UPDATED_DATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_REPLY;
SELECT * FROM TBL_REPLY;